@host = http://localhost:3000

GET {{host}}

@User = http://localhost:3000/user

###
GET {{User}}

###
GET {{User}}?username=bubu

###
GET {{User}}?email=eje

###
POST {{User}}
Content-Type: application/json

{
    "username": "algoEjemplo",
    "email": "ejemplo@ejemplo.com",
    "password": "1234"
}

###
POST {{User}}
Content-Type: application/json

{
    "username": "Bubulubu",
    "email": "bubu@ejemplo.com",
    "password": "2627"
}


###
PUT {{User}}/Ot295lVEkTg2Kgu_SKgPB
Content-Type: application/json

{
    "username": "Bubu Cambiado",
    "password": "2627"
}

###
DELETE {{User}}/_dEHfzXjlB1gToorrzHbi

###################################################
###################################################

@login = http://localhost:3000/user/login

###
GET {{login}}
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJ1YnVAZWplbXBsby5jb20iLCJpYXQiOjE3MDA0NjE1MDgsImV4cCI6MTcwMDQ2MjEwOH0.JACjyJX4MpnNOgJT9sP6EPwaRVCGISMDwuYc_wrr_I0


//12345
###

POST {{login}}
Content-Type: application/json

{
    "email": "bubu@ejemplo.com",
    "password": "2627"
}
