@host = http://localhost:3000

GET {{host}}

@User = http://localhost:3000/user

###
GET {{User}}

###
GET {{User}}?username=bubueno

###
GET {{User}}?email=txt

###
POST {{User}}
Content-Type: application/json

{
    "username": "algoEjemplo",
    "email": "ejemplo@ejemplo.com",
    "password": "1234"
}

###
PUT {{User}}/6tpFl-kJ4YY1MgXUPkZsU
Content-Type: application/json

{
    "username": "Bubu Cambiado",
    "password": "2627"
}

###
DELETE {{User}}/6tpFl-kJ4YY1MgXUPkZsU

###################################################
###################################################

@login = http://localhost:3000/user/login

###
GET {{login}}
x-token: 

###

POST {{login}}
Content-Type: application/json

{
    "email": "bubu@ejemplo.com",
    "password": "2627"
}

###################################################
###################################################
@add = http://localhost:3000/user/add

POST {{add}}
Content-Type: application/json

{
    "email": "bubu@ejemplo.com",
    "uuid": "gb3D6CWVphrgbqojGssMZ"
}